// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package notifierhub

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TorrentTask struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Size                 int64    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Type                 string   `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Rest                 string   `protobuf:"bytes,5,opt,name=rest,proto3" json:"rest,omitempty"`
	Hash                 string   `protobuf:"bytes,6,opt,name=hash,proto3" json:"hash,omitempty"`
	Startts              int64    `protobuf:"varint,7,opt,name=startts,proto3" json:"startts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TorrentTask) Reset()         { *m = TorrentTask{} }
func (m *TorrentTask) String() string { return proto.CompactTextString(m) }
func (*TorrentTask) ProtoMessage()    {}
func (*TorrentTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *TorrentTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TorrentTask.Unmarshal(m, b)
}
func (m *TorrentTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TorrentTask.Marshal(b, m, deterministic)
}
func (m *TorrentTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TorrentTask.Merge(m, src)
}
func (m *TorrentTask) XXX_Size() int {
	return xxx_messageInfo_TorrentTask.Size(m)
}
func (m *TorrentTask) XXX_DiscardUnknown() {
	xxx_messageInfo_TorrentTask.DiscardUnknown(m)
}

var xxx_messageInfo_TorrentTask proto.InternalMessageInfo

func (m *TorrentTask) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TorrentTask) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *TorrentTask) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *TorrentTask) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TorrentTask) GetRest() string {
	if m != nil {
		return m.Rest
	}
	return ""
}

func (m *TorrentTask) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *TorrentTask) GetStartts() int64 {
	if m != nil {
		return m.Startts
	}
	return 0
}

func init() {
	proto.RegisterType((*TorrentTask)(nil), "notifierhub.TorrentTask")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 157 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x34, 0xce, 0x31, 0xaa, 0xc3, 0x30,
	0x0c, 0x80, 0x61, 0xfc, 0x92, 0x97, 0x50, 0x67, 0xf3, 0xa4, 0x31, 0x74, 0xca, 0xd4, 0xa5, 0x37,
	0x09, 0xb9, 0x80, 0x43, 0x55, 0x6c, 0x02, 0xb1, 0x91, 0xe4, 0xa1, 0xbd, 0x4c, 0xaf, 0x5a, 0x64,
	0xd3, 0xed, 0xd7, 0x87, 0x10, 0xb2, 0x56, 0x3c, 0x1f, 0xb7, 0x4c, 0x49, 0x92, 0x9b, 0xce, 0x24,
	0xf1, 0x19, 0x91, 0x42, 0xd9, 0xaf, 0x1f, 0x63, 0xa7, 0x2d, 0x11, 0xe1, 0x29, 0x9b, 0xe7, 0xc3,
	0x39, 0xdb, 0x97, 0x12, 0x1f, 0x60, 0x66, 0xb3, 0x5c, 0xd6, 0xda, 0x6a, 0xd9, 0x4b, 0x80, 0xbf,
	0x66, 0xda, 0x6a, 0x1c, 0xdf, 0x08, 0xdd, 0x6c, 0x96, 0x6e, 0xad, 0xad, 0x26, 0xaf, 0x8c, 0xd0,
	0xb7, 0x3d, 0x6d, 0x35, 0x42, 0x16, 0xf8, 0x6f, 0xa6, 0xad, 0x16, 0x3c, 0x07, 0x18, 0x9a, 0x69,
	0x3b, 0xb0, 0x23, 0x8b, 0x27, 0x11, 0x86, 0xb1, 0x9e, 0xfc, 0x8d, 0xfb, 0x50, 0xbf, 0xbe, 0x7f,
	0x03, 0x00, 0x00, 0xff, 0xff, 0xe9, 0x88, 0xfc, 0x8b, 0xc3, 0x00, 0x00, 0x00,
}
